# Generated by Django 4.2.20 on 2025-04-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfiles',
            old_name='file',
            new_name='file_field',
        ),
    ]
