# Generated by Django 4.2.20 on 2025-06-06 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_postjobmodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_files', to='job.postjobmodel'),
        ),
        migrations.AlterField(
            model_name='uploadedfiles',
            name='user',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
