# Generated by Django 4.2.20 on 2025-04-20 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_rename_file_uploadedfiles_file_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfiles",
            name="description",
        ),
    ]
