# Generated by Django 4.2.20 on 2025-07-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_uploadedfiles_job_alter_uploadedfiles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='extracted_resume_skills',
            field=models.JSONField(default=list),
        ),
    ]
