# Generated by Django 4.2.20 on 2025-07-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_uploadedfiles_extracted_resume_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='college_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='company_names',
            field=models.TextField(blank=True, help_text='Comma-separated list of company names', null=True),
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='total_experience',
            field=models.FloatField(blank=True, help_text='Total experience in years', null=True),
        ),
    ]
