# Generated by Django 4.2.20 on 2025-04-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_remove_uploadedfiles_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostJobModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=100)),
                ("job_description", models.TextField(max_length=1000)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FT", "Full Time"),
                            ("PT", "Part Time"),
                            ("FR", "Free Lance"),
                            ("IN", "Internship"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
