# Generated by Django 4.2.20 on 2025-08-01 07:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_uploadedfiles_college_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
