# Generated by Django 4.2.20 on 2025-08-01 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_uploadedfiles_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
