# Generated by Django 4.2.20 on 2025-07-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_postjobmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjobmodel',
            name='extracted_skills',
            field=models.JSONField(default=list),
        ),
    ]
