# Generated by Django 4.2.20 on 2025-07-14 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_postjobmodel_extracted_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjobmodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postjobmodel',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postjobmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postjobmodel',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Entry-Level', 'Entry-Level'), ('Mid-Level', 'Mid-Level'), ('Senior-Level', 'Senior-Level')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='postjobmodel',
            name='industry',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postjobmodel',
            name='max_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postjobmodel',
            name='min_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postjobmodel',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=20, null=True),
        ),
    ]
