# Generated by Django 4.2.20 on 2025-07-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_postjobmodel_city_postjobmodel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjobmodel',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=10),
        ),
    ]
